# Generated by Django 5.1.1 on 2024-12-19 10:41

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=255)),
                ('short_description', tinymce.models.HTMLField(help_text='This will be shown on the home page.')),
                ('long_description', tinymce.models.HTMLField(help_text='This will be shown on the detailed page.')),
                ('infrastructure', tinymce.models.HTMLField(verbose_name='Infrastructure of APON')),
                ('membership_affiliation', tinymce.models.HTMLField(verbose_name='Membership & Affiliation')),
                ('awards', tinymce.models.HTMLField(verbose_name='Awards')),
                ('goal', tinymce.models.HTMLField(verbose_name='Goal')),
                ('objectives', tinymce.models.HTMLField(verbose_name='Objectives of APON')),
                ('program_activities', tinymce.models.HTMLField(verbose_name='Program Activities')),
                ('main_image', models.ImageField(default='path/to/default/main_image.jpg', help_text='Main image for the home page.', upload_to='about_us/')),
                ('additional_images', models.ImageField(blank=True, help_text='Additional images for the detailed page.', null=True, upload_to='about_us/')),
            ],
            options={
                'verbose_name': 'About Us Section',
                'verbose_name_plural': 'About Us Section',
            },
        ),
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel_images/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Name of the Material Icon (e.g., event, people).', max_length=100)),
                ('number', models.CharField(help_text="Number to display, e.g., '26', '1500+', etc.", max_length=100)),
                ('label', models.CharField(help_text="Label for the fact (e.g., 'YEARS').", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField()),
                ('image', models.ImageField(upload_to='news_images/')),
                ('published_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='services/')),
                ('short_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='team_images/')),
            ],
        ),
    ]
